### ISSUE TITLE
Undo doesn't work 

### ISSUE THREAD

**Issue by fsam95** [amgrubb/BloomingLeaf#1]
Steps to duplicate: 
1) Add a new task to the canvas
2) Press undo
Expected behaviour: Task disappears
Actual behaviour: Nothing happens

**Comment by Akira83** [comment]
This problem seems to occur in the third party JS library joint.dia.command.js. Here is a stacktrace of the bug:

revertCommand file:///home/marcel/git/BloomingLeaf/leaf-ui/rappid/dist/joint.dia.command.js:294:21
undo file:///home/marcel/git/BloomingLeaf/leaf-ui/rappid/dist/joint.dia.command.js:346:13
r file:///home/marcel/git/BloomingLeaf/leaf-ui/rappid/lib/lodash/lodash.min.js:26:88
dispatch file:///home/marcel/git/BloomingLeaf/leaf-ui/rappid/lib/jquery/jquery.min.js:5:9954
add/y.handle file:///home/marcel/git/BloomingLeaf/leaf-ui/rappid/lib/jquery/jquery.min.js:5:6772

Since it is not in our code I will verify if there is a work around later.
