### ISSUE TITLE
Add Undefined and Nonexistent

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#127]
We need to add two new dynamic functions to the tool.

Undefined (U <- identifier for passing to backend, associated value is None (T,T) or 0000)
Nonexistent (N <- identifier for passing to backend, associated value is None (T,T) or 0000)

![screen shot 2018-04-13 at 1 53 22 pm](https://user-images.githubusercontent.com/6596937/38752399-ffed396e-3f28-11e8-9029-b14253d51b79.png)

They should be added to both the UD function list and the broader function list.

And passed to the backend. Representing them in the results will take some discussion. Let's start with the first part.

Differentiate between None, Undefined, and Nonexistent.

Implement a presence/existence time frame slider on Model view.

**Comment by amgrubb** [comment]
Connected with #155 
Needed for formal merge.

**Comment by oibrahim22** [comment]
and deleted

**Comment by oibrahim22** [comment]
Adding undefined and nonexistent in the frontend it is easy. Currently, the backend evaluation label is a 4 digit binary string and all possible combinations already represent a value (ex 0000 is none ).  We need to either change the way we represent values in the backend or expand on it so that more values can be represented uniquely such as undefined, nonexistent, deleted and no value.

**Comment by amgrubb** [comment]
We are going to create a new issue and redescribed the problem.
