### ISSUE TITLE
[Deprecation] Synchronous XMLHttpRequest

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#160]
Branch: Develop 

The following error appears when I clicked Analysis to switch views.

![screen shot 2018-10-04 at 1 41 41 pm](https://user-images.githubusercontent.com/6596937/46492359-4ee20280-c7db-11e8-940d-f8e723083e48.png)

**Comment by amgrubb** [comment]
Still an issue.

**Comment by oibrahim22** [comment]
This issue occurs in the jquery.js file which is in rappid folder. The issue is caused by setting the async value to false(line 9311). "Synchronous XMLHttpRequest outside of workers is in the process of being removed from the web platform as it has detrimental effects to the end user’s experience. (This is a long process that takes many years.) Developers must not pass false for the async argument when current global object is a Window object. User agents are strongly encouraged to warn about such usage in developer tools and may experiment with throwing an "InvalidAccessError" DOMException when it occurs." https://xhr.spec.whatwg.org/#the-open()-method. To fix we can change the value to true

**Comment by amgrubb** [comment]
The file is:
`rappid/node_modules/jquery/dist/jquery.js`
line `9311`:
`async: false,`
can be changed to true
