### ISSUE TITLE
Change .onreadystatechange to .onload in Node.js call.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#195]
The newer event handler is .onload. The link below explain both .onload and .onreadystatechange.
https://javascript.info/xmlhttprequest 
 
I can't find it now but in some other source they suggested that .onload is not necessarily supported by all browsers.

**Comment by Vbeany** [comment]
The onreadystatechange event is mainly used to track xhr.readyState. Meaning It tracks the state at which something is loaded and it’s progress. E.g. 0 meaning It hasn’t been sent, 1 being it has been opened, 2 response headers received, 3 response is loading and 4 showing the request is completed. More info about states here: (https://xhr.spec.whatwg.org/#states) 

The onload event loads the request entirely. It waits for everything to be loaded. E.g. Onload event takes longer to load because it waits for the image to fully load in the image tag. 

In the article it mentions three main events that are widely used in XMLHttpRequest, load/error/progress (onload being one of them). I also looked onto another website and it seems that onload was compatible with most browsers. (https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event)
(https://www.w3schools.com/jsref/event_onload.asp)

It seems that readystatechange can now be replaced with newer events as most newer events do the same job. In the article it mentioned how readystatechange is commonly found in older code. But load/error/progress handlers now do almost the same exact thing as Readystatechange events.

**Comment by amgrubb** [comment]
Great, can you change 
`xhr.onreadystatechange = function () {` on line 26 of `backendComm.js`
to be:
`xhr.onload = function () {`
and then test it thoroughly to make sure the calls to the backend still work?
