### ISSUE TITLE
Conflict prevention level not visible

### ISSUE THREAD

**Issue by esterzhao** [amgrubb/BloomingLeaf#272]
When loading in analysis, while the conflict prevention level is accurate set, it isn't visible on the Configuration 1.

![Screen Shot 2021-02-04 at 5 03 12 PM](https://user-images.githubusercontent.com/37080292/106961083-17692500-670b-11eb-9fe4-a5a637594e95.png)

![Screen Shot 2021-02-04 at 5 05 08 PM](https://user-images.githubusercontent.com/37080292/106961131-26e86e00-670b-11eb-887b-64f4ba3e905b.png)

**Comment by leshghi** [comment]
@esterzhao I am having trouble recreating this bug, could you do a demo/add some more screenshots/share the upload file you used at some point? No rush at all!

**Comment by leshghi** [comment]
Issue caused by faulty json file (scheduler.json) where the conflict prevention level is saved as "A" which is not an option on the dropdown menu, causing the blank option shown in the UI. The checkmark on strong is because the UI is rendered that way until another option is selected, which has not occurred since A is not a true option in the html. Coincidentally, this also causes the 10 in the Num Relative Time Points, which is different than the typical 1.
