### ISSUE TITLE
Create a variable for the type of analysis.

### ISSUE THREAD

**Issue by Akira83** [amgrubb/BloomingLeaf#29]
In the frontend we have the flags "solveSinglePath" and "getNextState" that determines the two types of analysis. Refactor this two attributes in order to have only one that could be called "typeOfAnalysis" and receive the string "singlePath" and "getNextState" as values.

In the backend it will impact the classes InputAnalysis and the ModelSpecBuilder.

**Comment by amgrubb** [comment]
It would be one variable in ModelSpec as well. Then I will update how TroposCSPAlgorithm interacts with the new variable. Call it analysisType instead of typeofAnalysis.

The possible types of analysis in ModelSpec.analysisType should be:
"singlePath"
"allNextState"
Remove Single.


In the front-end, in the analysis view I think the buttons should say:
"1. Simulate Single Path"
"2. Explore Possible Next States"
![screen shot 2017-08-24 at 9 25 37 am](https://user-images.githubusercontent.com/6596937/29668453-39aa0696-88ae-11e7-9300-d2d005db4e6a.png)

**Comment by Akira83** [comment]
Added a new attribute analysis.action that will have the type of analysis, solveSinglePath or allNextStates. Also changed the frontend analysis view buttons.
Next step is refactor backend to work with this new attribute.

**Comment by Akira83** [comment]
I will close this.

**Comment by amgrubb** [comment]
I am going to fix this in the solver now.
