### ISSUE TITLE
NotBoth Link not updating.

### ISSUE THREAD

**Issue by amgrubb** [amgrubb/BloomingLeaf#4]
NotBoth Links (both NBT and NBD) are not updating properly. This bug is intermittent. In the attached image Expropriate All Land Segments seems to have save but Build Design A/B did not.

![screen shot 2017-08-14 at 11 17 35 am](https://user-images.githubusercontent.com/6596937/29279589-4d92da7c-80e6-11e7-9ff6-b4551cd1d5f2.png)

Issues to result:

- [ ] NB value on model does does not appear.
- [ ] These values do not save properly when switching between analysis view.
- [ ] When passed to the backend, multiple pieces of data are missing.
`      {
        "nodeActorID": "-",
        "nodeID": "0029",
        "nodeType": "T",
        "nodeName": "Build Design A"
      },`
is missing
`        "initialValue": "0000",`
and
`      {
        "intentionID": "0029",
        "dynamicType": "NT",
        "line": null
      },`
has an error, and should be 
`"dynamicType": "NB",`
and is missing
`"markedValue": "0000",` for "NBT" and 
`"markedValue": "1100",` for "NBD".

The solver will not run without this information.

**Comment by Akira83** [comment]
- [ ]  NB value on model does does not appear.
Could not reproduce this problem. I will execute some more tests.

- [ ] These values do not save properly when switching between analysis view.
If this is related to the "View List of Assigments" table, I belive that is already correct in the marcel-dev branch.

- [ ] When passed to the backend, multiple pieces of data are missing.
- Corrected these missing intentions information for "initialValue".
- Corrected the value of "dynamicType" for dynamics.
- Added new attribute "markedValue" for links of type "NBT" and "NBD". 

Since some attributes are new backend modifications are necessary.

**Comment by amgrubb** [comment]
I still need to test this.

**Comment by amgrubb** [comment]
There are still bugs here.

- [ ] When I delete the link the labels still appear.
![screen shot 2017-08-17 at 10 31 52 am](https://user-images.githubusercontent.com/6596937/29417646-e68765ba-8337-11e7-8615-691609c2a62a.png)

- [ ] When I call the backend, there is a bug to create the backend file.
![screen shot 2017-08-17 at 10 34 09 am](https://user-images.githubusercontent.com/6596937/29417677-095d9d02-8338-11e7-81a4-38b8c49bb356.png)

**Comment by Akira83** [comment]
I will work only in this one for now... will need to do a bunch of refactorings... the code that updates the model is spread in at least 4 files. I will dig deep and see if I can modularize this changes in only one place then it will be easy to understand what is going on.
