### ISSUE TITLE
parentNode null for intention with certain function type 

### ISSUE THREAD

**Issue by YesugenB** [amgrubb/BloomingLeaf#607]
I think for any intention if the function type is RC or CR and you touch/try to move it, you get this error

<img width="1391" alt="Screen Shot 2021-10-23 at 7 34 17 PM" src="https://user-images.githubusercontent.com/59470488/138574498-7871e9f7-bbe3-4fa8-ac8d-a29fa8bd9958.png">

_Originally posted by @YesugenB in https://github.com/amgrubb/BloomingLeaf/issues/605#issuecomment-950232158_

**Comment by i-m-foster** [comment]
This error also happens if you have a constant function, switch the initial satisfaction value, and then try to move it

**Comment by Domily11** [comment]
This error also happens if you chose the function type, stimulated a path, and then tried to change the function type again

**Comment by Domily11** [comment]
What we figured out: every time the ElementInspector is called, Chart gets updated several times. The reason why even after there is an error the website is still functioning like it's supposed to be is because the error happens in one of the calls in the middle, which is later replaced again by a fully functioning chart. We know that the function segments affects the chart every time it is changed or new segments are added, but we have not figured out why sometimes the chart seems to be called more times than the number of function segments that are present, and why there is an error in some of the calls.

**Comment by Domily11** [comment]
This error also happens if you set the initial satisfaction value to satisfied, set the function type as constant-stochastic or stochastic constant, click on the page, then click on the intention again

**Comment by YanningTan** [comment]
> This error also happens if you set the initial satisfaction value to satisfied, set the function type as constant-stochastic or stochastic constant, click on the page, then click on the intention again

This error happens whatever the initial satisfaction value you set (except no value), set the function type as constant-stochastic or stochastic constant, click on the page, then click on the intention again

**Comment by YanningTan** [comment]
This error also happens when you try to switch between SD and DS. Set the function type as SD, click on the page, then click on the intention again and set the function type as DS, and vice versa.

**Comment by cbenayed** [comment]
Unable to reproduce bug
