### ISSUE TITLE
Implement rules for Intermediate Value Table rows for Dynamic Function Type values

### ISSUE THREAD

**Issue by g2hchang** [amgrubb/BloomingLeaf#93]
1. Come up with all the rules.
2. Implement them in the code.

**Comment by amgrubb** [comment]
Dependent on #57.
Table has been created.

**Comment by oibrahim22** [comment]
This issue was fixed by editing loadIntermediateValue function in AnalysisInspector.js file. Now, the function checks if the user has assigned time points (if needed ) and gives the user a list of valid options for values based on the time point, the function type, and previous values and end value.
